title: "Travel Hacks Guide"
description: "2024's Cheapest Travel Secrets - Free Checklist Inside"
url: "https://travelhacksguide.space" # Your exact domain
remote_theme: mmistakes/minimal-mistakes
affiliate_links:
  amazon: "nomadhacks-20" # Default placeholder
  booking: "123456" # Placeholder
